"use client";
import React from "react";
export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 to-blue-900 text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">test real</h1>
          <p className="text-xl text-blue-200">AI-Generated Production System</p>
        </div>
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Features</h2>
          <div className="grid md:grid-cols-2 gap-4">
            <a href="/pipelines" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Pipelines</h3>
              <p className="text-blue-200 text-sm">Navigate to /pipelines</p>
            </a>
            <a href="/ai-integrations" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Ai integrations</h3>
              <p className="text-blue-200 text-sm">Navigate to /ai-integrations</p>
            </a>
          </div>
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">System Overview</h2>
            <p className="text-blue-100">This system was automatically generated by Dev AI from a Business Requirements Document (BRD).</p>
          </div>
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">Built With</h2>
            <ul className="text-blue-100 space-y-2">
              <li>Next.js 14</li>
              <li>TypeScript</li>
              <li>Tailwind CSS</li>
              <li>Supabase (Database)</li>
            </ul>
          </div>
        </div>
      </div>
    </main>
  );
}
